# Generated by Django 3.0.5 on 2020-06-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20200610_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
