# Generated by Django 3.0.5 on 2020-09-22 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
